//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IBSDKFunctionTester.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_IBSDKFUNCTIONTESTER_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDI_ICON_ON                     132
#define IDI_ICON_OFF                    133
#define IDB_BITMAP_LOGO                 134
#define IDC_TAB1                        1000
#define IDC_STATIC_MAIN                 1002
#define IDC_BUTTON_SDKVERSION           1003
#define IDC_BUTTON_GETDEVICECOUNT       1004
#define IDC_LIST_MAIN                   1005
#define IDC_COMBO_DEVICE                1006
#define IDC_COMBO_C                     1007
#define IDC_BUTTON_DEVICEDESCRIPTION    1008
#define IDC_BUTTON_OPENDEVICE           1009
#define IDC_BUTTON_DEVICECLOSE          1010
#define IDC_BUTTON_ISDEVICEOPEN         1011
#define IDC_BUTTON_GETPROPERTY          1012
#define IDC_COMBO_PROPERTY              1013
#define IDC_BUTTON_SETPROPERTY          1014
#define IDC_EDIT_SETPROPERTY            1015
#define IDC_BUTTON_OPENDEVICE2          1016
#define IDC_BUTTON_AGING_TEST           1016
#define IDC_STATIC_IMAGE                1018
#define IDC_BUTTON_ISCAPTUREAVAILABLE   1019
#define IDC_BUTTON_START                1020
#define IDC_BUTTON_STOP                 1021
#define IDC_FRAME_IMAGE                 1022
#define IDC_CHECK_CLIENT_WINDOW         1023
#define IDC_CHECK_SAVE_IMAGES           1024
#define IDC_BTN_IMAGE_FOLDER            1025
#define IDC_CHECK__AUTO_CONTRAST        1026
#define IDC_CHECK_AUTO_CAPTURE          1027
#define IDC_CHECK_IGNORE_FINGER_COUNT   1028
#define IDC_COMBO_ISCAPTUREAVAILABLE    1029
#define IDC_STATIC_IMAGETYPE            1030
#define IDC_BUTTON_ISCAPTUREACTIVE      1031
#define IDC_BUTTON_GETCONTRAST          1032
#define IDC_BUTTON_SETCONTRAST          1033
#define IDC_EDIT_SETCONTRAST            1034
#define IDC_BUTTON_GETLEOPERATIONMODE   1035
#define IDC_BUTTON_SETLEOPERATION       1036
#define IDC_COMBO_SETLEOPERATIONMODE    1038
#define IDC_BUTTON_ISTOUCHFINGER        1039
#define IDC_BUTTON_GETOPERABLELEDS      1040
#define IDC_BUTTON_GETLEDS              1041
#define IDC_BUTTON_SETLEDS              1042
#define IDC_COMBO_SETLEDS               1043
#define IDC_STATIC_CAPTURE              1044
#define IDC_STATIC_DEVICE               1045
#define IDC_STATIC_TYPE                 1046
#define IDC_STATIC_HANDLE               1046
#define IDC_STATIC_CALLBACK             1047
#define IDC_ICON_DCOMBRE_ON             1048
#define IDC_ICON_DCOMBRE_OFF            1049
#define IDC_STATIC_DCOMBRE              1050
#define IDC_ICON_PREVIEWIMAGE_ON        1051
#define IDC_ICON_PREVIEWIMAGE_OFF       1052
#define IDC_STATIC_PREVIEWIMAGE         1053
#define IDC_ICON_TAKINGACQUISITION_ON   1054
#define IDC_ICON_TAKINGACQUISITION_OFF  1055
#define IDC_STATIC_TAKINGACQUISITION    1056
#define IDC_ICON_RESULTIMAGE_ON         1057
#define IDC_ICON_RESULTIMAGE_OFF        1058
#define IDC_STATIC_RESULTIMAGE          1059
#define IDC_ICON_COMPLETEACQUISITION_ON 1060
#define IDC_ICON_COMPLETEACQUISITION_OFF 1061
#define IDC_STATIC_COMPLETEACQUISITION  1062
#define IDC_ICON_FINGERCOUNT_ON         1063
#define IDC_ICON_FINGERCOUNT_OFF        1064
#define IDC_STATIC_FINGERCOUNT          1065
#define IDC_ICON_FINGERQUALITY_ON       1066
#define IDC_ICON_FINGERQUALITY_OFF      1067
#define IDC_STATIC_FINGERQUALITY        1068
#define IDC_ICON_DEVICECOUNT_ON         1069
#define IDC_ICON_DEVICECOUNT_OFF        1070
#define IDC_STATIC_DEVICECOUNT          1071
#define IDC_ICON_INITPROGRESS_ON        1072
#define IDC_ICON_INITPROGRESS_OFF       1073
#define IDC_STATIC_INITPROGRESS         1074
#define IDC_STATIC_BACKCL               1075
#define IDC_EDIT_SETBACKCL              1076
#define IDC_CHECK_GUIDELINE             1079
#define IDC_STATIC_FONTSIZE             1080
#define IDC_EDIT_FONTSIZE               1081
#define IDC_CHECK_BOLD                  1082
#define IDC_STATIC_POSX                 1083
#define IDC_STATIC_POSY                 1084
#define IDC_EDIT_POSX                   1085
#define IDC_EDIT_POSY                   1086
#define IDC_STATIC_TEXTCOLOR            1087
#define IDC_EDIT_TEXTCOLOR              1088
#define IDC_STATIC_DISPLAY              1089
#define IDC_STATIC_TEXT                 1090
#define IDC_EDIT_INITPROGRESS           1091
#define IDC_EDIT_FINGERCOUNT            1092
#define IDC_EDIT_FINGERQUALITY          1093
#define IDC_EDIT_DEVICECOUNT            1094
#define IDC_STATIC_SETCONTRAST          1095
#define IDC_STATIC_BACKCOLOR            1096
#define IDC_EDIT_PREVIEWIMAGE           1097
#define IDC_STATIC_RED                  1098
#define IDC_STATIC_GREEN                1099
#define IDC_EDIT_GREEN                  1100
#define IDC_STATIC_BLACK                1101
#define IDC_EDIT_BLACK                  1102
#define IDC_STATIC_BETWEEN              1103
#define IDC_EDIT_DEVICE                 1104
#define IDC_EDIT_CAPTURETYPE            1105
#define IDC_EDIT_HANDLE                 1105
#define IDC_EDIT_ADDTEXT                1106
#define IDC_STATIC_ADDTEXT              1107
#define IDC_CHECK_FINGERCOUNT           1108
#define IDC_CHECK_CLEARPLATE            1109
#define IDC_EDIT_PREVIEWIMAGE2          1109
#define IDC_EDIT_RESULTIMAGE            1109
#define IDC_STATIC_MAININTERFACE        1110
#define IDC_STATIC_LEOPERATION          1111
#define IDC_STATIC_LED                  1112
#define IDC_STATIC_CONTRAST             1113
#define IDC_STATIC_ICON_CLEARPLATE_ON   1114
#define IDC_ICON_CLEARPLATE_ON          1114
#define IDC_STATIC_ICON_CLEARPLATE_OFF  1115
#define IDC_ICON_CLEARPLATE_OFF         1115
#define IDC_STATIC_CLEARPLATE           1116
#define IDC_EDIT1                       1117
#define IDC_EDIT_CLEARPLATE             1117
#define IDC_STATIC_LOGO                 1118
#define IDC_LIST_ETC                    1119
#define IDC_EDIT_BKRED                  1120
#define IDC_EDIT_BKGREEN                1121
#define IDC_EDIT_BKBLUE                 1122
#define IDC_STATIC_BKRED                1123
#define IDC_STATIC_BKGREEN              1124
#define IDC_STATIC_BKBLUE               1125
#define IDC_STATIC_BKRANGE              1126
#define IDC_BUTTON_MANUALCAPTURE        1127
#define c                               1127
#define IDC_CHECK1                      1128
#define IDC_CHECK_APPENDRESULT          1128
#define IDC_EDIT_SETLED                 1129
#define IDC_STATIC_HEX                  1130
#define IDC_BUTTON_BACKCL               1131
#define IDC_BUTTON_SET_DISPLAY_OVERLAY_TEXT 1132
#define IDC_BUTTON1                     1135

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1136
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
