# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IBSU_SampleForPySide.ui'
#
# Created: Wed Nov 29 00:02:49 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import Images

class Ui_IBSU_SampleForPySide(object):
    def setupUi(self, IBSU_SampleForPySide):
        IBSU_SampleForPySide.setObjectName("IBSU_SampleForPySide")
        IBSU_SampleForPySide.setEnabled(True)
        IBSU_SampleForPySide.resize(772, 553)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        IBSU_SampleForPySide.setFont(font)
        IBSU_SampleForPySide.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        IBSU_SampleForPySide.setAnimated(True)
        self.centralWidget = QtGui.QWidget(IBSU_SampleForPySide)
        self.centralWidget.setObjectName("centralWidget")
        self.m_FrameImage = QtGui.QLabel(self.centralWidget)
        self.m_FrameImage.setGeometry(QtCore.QRect(300, 80, 461, 431))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_FrameImage.setFont(font)
        self.m_FrameImage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_FrameImage.setFrameShape(QtGui.QFrame.Panel)
        self.m_FrameImage.setFrameShadow(QtGui.QFrame.Sunken)
        self.m_FrameImage.setText("")
        self.m_FrameImage.setObjectName("m_FrameImage")
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox.setObjectName("groupBox")
        self.m_cboUsbDevices = QtGui.QComboBox(self.groupBox)
        self.m_cboUsbDevices.setGeometry(QtCore.QRect(10, 20, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_cboUsbDevices.setFont(font)
        self.m_cboUsbDevices.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_cboUsbDevices.setObjectName("m_cboUsbDevices")
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 281, 211))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox_2.setObjectName("groupBox_2")
        self.m_cboCaptureSeq = QtGui.QComboBox(self.groupBox_2)
        self.m_cboCaptureSeq.setGeometry(QtCore.QRect(10, 20, 261, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_cboCaptureSeq.setFont(font)
        self.m_cboCaptureSeq.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_cboCaptureSeq.setObjectName("m_cboCaptureSeq")
        self.m_chkIgnoreFingerCount = QtGui.QCheckBox(self.groupBox_2)
        self.m_chkIgnoreFingerCount.setGeometry(QtCore.QRect(10, 90, 261, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_chkIgnoreFingerCount.setFont(font)
        self.m_chkIgnoreFingerCount.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_chkIgnoreFingerCount.setChecked(False)
        self.m_chkIgnoreFingerCount.setObjectName("m_chkIgnoreFingerCount")
        self.m_chkAutoCapture = QtGui.QCheckBox(self.groupBox_2)
        self.m_chkAutoCapture.setGeometry(QtCore.QRect(10, 70, 261, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_chkAutoCapture.setFont(font)
        self.m_chkAutoCapture.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_chkAutoCapture.setChecked(True)
        self.m_chkAutoCapture.setObjectName("m_chkAutoCapture")
        self.m_chkAutoContrast = QtGui.QCheckBox(self.groupBox_2)
        self.m_chkAutoContrast.setGeometry(QtCore.QRect(10, 50, 261, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_chkAutoContrast.setFont(font)
        self.m_chkAutoContrast.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_chkAutoContrast.setChecked(True)
        self.m_chkAutoContrast.setObjectName("m_chkAutoContrast")
        self.m_btnCaptureStart = QtGui.QPushButton(self.groupBox_2)
        self.m_btnCaptureStart.setGeometry(QtCore.QRect(160, 150, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_btnCaptureStart.setFont(font)
        self.m_btnCaptureStart.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_btnCaptureStart.setObjectName("m_btnCaptureStart")
        self.m_btnCaptureStop = QtGui.QPushButton(self.groupBox_2)
        self.m_btnCaptureStop.setGeometry(QtCore.QRect(10, 150, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_btnCaptureStop.setFont(font)
        self.m_btnCaptureStop.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_btnCaptureStop.setObjectName("m_btnCaptureStop")
        self.m_sliderContrast = QtGui.QSlider(self.groupBox_2)
        self.m_sliderContrast.setGeometry(QtCore.QRect(60, 180, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_sliderContrast.setFont(font)
        self.m_sliderContrast.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_sliderContrast.setOrientation(QtCore.Qt.Horizontal)
        self.m_sliderContrast.setObjectName("m_sliderContrast")
        self.Lable_Contrast = QtGui.QLabel(self.groupBox_2)
        self.Lable_Contrast.setGeometry(QtCore.QRect(10, 180, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.Lable_Contrast.setFont(font)
        self.Lable_Contrast.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Lable_Contrast.setObjectName("Lable_Contrast")
        self.m_chkSaveImges = QtGui.QCheckBox(self.groupBox_2)
        self.m_chkSaveImges.setEnabled(True)
        self.m_chkSaveImges.setGeometry(QtCore.QRect(10, 120, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_chkSaveImges.setFont(font)
        self.m_chkSaveImges.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_chkSaveImges.setObjectName("m_chkSaveImges")
        self.m_txtContrast = QtGui.QTextEdit(self.groupBox_2)
        self.m_txtContrast.setGeometry(QtCore.QRect(230, 180, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_txtContrast.setFont(font)
        self.m_txtContrast.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.m_txtContrast.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.m_txtContrast.setObjectName("m_txtContrast")
        self.m_btnImageFolder = QtGui.QPushButton(self.groupBox_2)
        self.m_btnImageFolder.setGeometry(QtCore.QRect(110, 120, 31, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_btnImageFolder.setFont(font)
        self.m_btnImageFolder.setObjectName("m_btnImageFolder")
        self.m_txtStatusMessage = QtGui.QLabel(self.centralWidget)
        self.m_txtStatusMessage.setGeometry(QtCore.QRect(10, 520, 751, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_txtStatusMessage.setFont(font)
        self.m_txtStatusMessage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_txtStatusMessage.setFrameShape(QtGui.QFrame.Panel)
        self.m_txtStatusMessage.setFrameShadow(QtGui.QFrame.Sunken)
        self.m_txtStatusMessage.setObjectName("m_txtStatusMessage")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 781, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Images/IB_logo.bmp"))
        self.label.setObjectName("label")
        self.groupBox_3 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 360, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(8, 14, 121, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Images/Scanner.bmp"))
        self.label_2.setObjectName("label_2")
        self.lblQuality_1 = QtGui.QLabel(self.groupBox_3)
        self.lblQuality_1.setGeometry(QtCore.QRect(24, 47, 20, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblQuality_1.setFont(font)
        self.lblQuality_1.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblQuality_1.setText("")
        self.lblQuality_1.setObjectName("lblQuality_1")
        self.lblQuality_2 = QtGui.QLabel(self.groupBox_3)
        self.lblQuality_2.setGeometry(QtCore.QRect(45, 47, 20, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblQuality_2.setFont(font)
        self.lblQuality_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblQuality_2.setText("")
        self.lblQuality_2.setObjectName("lblQuality_2")
        self.m_chkUseClearPlaten = QtGui.QCheckBox(self.centralWidget)
        self.m_chkUseClearPlaten.setGeometry(QtCore.QRect(150, 370, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_chkUseClearPlaten.setFont(font)
        self.m_chkUseClearPlaten.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_chkUseClearPlaten.setChecked(True)
        self.m_chkUseClearPlaten.setObjectName("m_chkUseClearPlaten")
        self.m_chkDrawSegmentImage = QtGui.QCheckBox(self.centralWidget)
        self.m_chkDrawSegmentImage.setGeometry(QtCore.QRect(150, 390, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_chkDrawSegmentImage.setFont(font)
        self.m_chkDrawSegmentImage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_chkDrawSegmentImage.setChecked(True)
        self.m_chkDrawSegmentImage.setObjectName("m_chkDrawSegmentImage")
        self.m_chkNFIQScore = QtGui.QCheckBox(self.centralWidget)
        self.m_chkNFIQScore.setGeometry(QtCore.QRect(150, 430, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_chkNFIQScore.setFont(font)
        self.m_chkNFIQScore.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_chkNFIQScore.setChecked(True)
        self.m_chkNFIQScore.setObjectName("m_chkNFIQScore")
        self.m_txtNFIQScore = QtGui.QLabel(self.centralWidget)
        self.m_txtNFIQScore.setGeometry(QtCore.QRect(220, 430, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_txtNFIQScore.setFont(font)
        self.m_txtNFIQScore.setFrameShape(QtGui.QFrame.Panel)
        self.m_txtNFIQScore.setFrameShadow(QtGui.QFrame.Sunken)
        self.m_txtNFIQScore.setText("")
        self.m_txtNFIQScore.setObjectName("m_txtNFIQScore")
        self.m_chkInvalidArea = QtGui.QCheckBox(self.centralWidget)
        self.m_chkInvalidArea.setEnabled(False)
        self.m_chkInvalidArea.setGeometry(QtCore.QRect(150, 460, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_chkInvalidArea.setFont(font)
        self.m_chkInvalidArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_chkInvalidArea.setChecked(False)
        self.m_chkInvalidArea.setObjectName("m_chkInvalidArea")
        self.m_chkDetectSmear = QtGui.QCheckBox(self.centralWidget)
        self.m_chkDetectSmear.setGeometry(QtCore.QRect(150, 480, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_chkDetectSmear.setFont(font)
        self.m_chkDetectSmear.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_chkDetectSmear.setChecked(True)
        self.m_chkDetectSmear.setObjectName("m_chkDetectSmear")
        self.m_cboSmearLevel = QtGui.QComboBox(self.centralWidget)
        self.m_cboSmearLevel.setGeometry(QtCore.QRect(240, 480, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.m_cboSmearLevel.setFont(font)
        self.m_cboSmearLevel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.m_cboSmearLevel.setObjectName("m_cboSmearLevel")
        self.m_txtDllVersion = QtGui.QLabel(self.centralWidget)
        self.m_txtDllVersion.setGeometry(QtCore.QRect(440, 25, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.m_txtDllVersion.setFont(font)
        self.m_txtDllVersion.setObjectName("m_txtDllVersion")
        self.m_txtCopyRight = QtGui.QLabel(self.centralWidget)
        self.m_txtCopyRight.setGeometry(QtCore.QRect(440, 50, 321, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.m_txtCopyRight.setFont(font)
        self.m_txtCopyRight.setObjectName("m_txtCopyRight")
        self.lblQuality_3 = QtGui.QLabel(self.centralWidget)
        self.lblQuality_3.setGeometry(QtCore.QRect(76, 407, 20, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblQuality_3.setFont(font)
        self.lblQuality_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblQuality_3.setText("")
        self.lblQuality_3.setObjectName("lblQuality_3")
        self.lblQuality_4 = QtGui.QLabel(self.centralWidget)
        self.lblQuality_4.setGeometry(QtCore.QRect(97, 407, 20, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblQuality_4.setFont(font)
        self.lblQuality_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblQuality_4.setText("")
        self.lblQuality_4.setObjectName("lblQuality_4")
        IBSU_SampleForPySide.setCentralWidget(self.centralWidget)

        self.retranslateUi(IBSU_SampleForPySide)
        QtCore.QMetaObject.connectSlotsByName(IBSU_SampleForPySide)

    def retranslateUi(self, IBSU_SampleForPySide):
        IBSU_SampleForPySide.setWindowTitle(QtGui.QApplication.translate("IBSU_SampleForPySide", "IntegrationSample for PySide", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("IBSU_SampleForPySide", "Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("IBSU_SampleForPySide", "Fingerprint Capture", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chkIgnoreFingerCount.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Trigger invalid finger count on auto-capture Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chkAutoCapture.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Automatic Capture for Fingerprints", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chkAutoContrast.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Automatic Contrast Optimizaiton", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnCaptureStart.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnCaptureStop.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.Lable_Contrast.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Contrast", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chkSaveImges.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Save Images", None, QtGui.QApplication.UnicodeUTF8))
        self.m_btnImageFolder.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.m_txtStatusMessage.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Ready", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("IBSU_SampleForPySide", "Device Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chkUseClearPlaten.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Detect clear platen", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chkDrawSegmentImage.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Draw quadrangle for \n"
"segment image", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chkNFIQScore.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "NFIQ", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chkInvalidArea.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Invalid area", None, QtGui.QApplication.UnicodeUTF8))
        self.m_chkDetectSmear.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "Detect smear", None, QtGui.QApplication.UnicodeUTF8))
        self.m_txtDllVersion.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">TextLabel</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.m_txtCopyRight.setText(QtGui.QApplication.translate("IBSU_SampleForPySide", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Copyright (c) Integrated Biometrics</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))



